### ISSUE TITLE
Sync only favorite tracks and no playlist

### ISSUE THREAD

**Issue by Sildenafil99** [timrae/spotify_to_tidal#73]
Hello and thanks for your work.
I tried using the tool but I can only synchronize favorite songs and not playlists.
Maybe I'm doing something wrong?

This is the output

PS C:\Temporary\spotify_to_tidal-main> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Login with the webbrowser: link.tidal.com/*****
Loading Spotify playlists
Loading playlists from Tidal user
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 6/6 [00:00<00:00, 27.29it/s]
Loading existing favorite tracks from Tidal
Searching Tidal for 122/122 tracks in Spotify playlist 'Favorites': 100%|████████████| 122/122 [00:15<00:00,  7.68it/s]
Could not find track 5ZKkEVSHfx6enyRJ7DFrFd: Junkie XL - Infinity
Could not find track 7g8pKtAeH3sKk75aKrIpDN: DJ Phellix,Johny Luv - Gentle Night
Could not find track 08FUzof6NqG8kQEsNmkWDh: Bronski Beat,Bourlingueurs - Smalltown Boy (Remix)
Could not find track 0bFaLfdRlQdgkg9MT7L8CQ: Edward Botero - No Man No Cry
Adding new tracks to Tidal favorites: 100%|██████████████████████████████████████████| 118/118 [00:17<00:00,  6.86it/s]
PS C:\Temporary\spotify_to_tidal-main>

**Comment by timrae** [comment]
What does your config file look like?

**Comment by Sildenafil99** [comment]
```
spotify:
  client_id: ef628a5c0fdb******************************
  client_secret: 353d393f85**************************
  username: 116*******
  redirect_uri: http://localhost:8888/callback


# uncomment this block if you want to only sync specific playlist IDs
#sync_playlists:
#  - spotify_id: 1ABCDEqsABCD6EaABCDa0a
#    tidal_id: a0b1234-0a1b-012a-abcd-a1b234c5d6d7

# uncomment this block if you want to sync all playlists in the account with some exceptions
#excluded_playlists:
#  - spotify:playlist:1ABCDEqsABCD6EaABCDa0a

# default setting for syncing favorites when no command line arguments are provided
#   - when true:  favorites will be synced by default (overriden when any command line arg provided)
#   - when false: favorites can only be synced manually via --sync-favorites argument
sync_favorites_default: true

# increasing these parameters should increase the search speed, while decreasing reduces likelihood of 429 errors
max_concurrency: 10 # max concurrent connections at any given time
rate_limit:      10 # max sustained connections per second
```

**Comment by timrae** [comment]
Everything looks fine to me, are you sure you logged into the correct account and you have playlists on that account that belong to you? (Playlists that belong to other people which you follow are not synced be default iirc)

**Comment by Sildenafil99** [comment]
Yes, I'm sure in fact it synchronizes my favorite songs, only the playlists don't.

With the spotify_to_tidal --uri  command I can synchronize the single playlist

Playlists are personal and not followed

**Comment by timrae** [comment]
I'm not sure then, it sounds like get_playlists_from_spotify() is returning an empty list for some reason [here](https://github.com/spotify2tidal/spotify_to_tidal/blob/main/src/spotify_to_tidal/sync.py#L361)? You could try deleting the .cache files and re-authorizing. If that doesn't work, you'll probably need to put some debugging statements to find the cause of the error

**Comment by Sildenafil99** [comment]
I tried deleting the cache.db file but nothing changed.
How can I start debugging?

**Comment by timrae** [comment]
Put `print(results)` just after this line:
https://github.com/spotify2tidal/spotify_to_tidal/blob/main/src/spotify_to_tidal/sync.py#L371

**Comment by timrae** [comment]
If that's returning an empty list perhaps there's an issue with your username somehow. You could try using  `current_user_playlists()` instead of `user_playlists()`:

```python
async def get_playlists_from_spotify(spotify_session: spotipy.Spotify, config):
    # get all the user playlists from the Spotify account
    playlists = []
    print("Loading Spotify playlists")
    results = spotify_session.current_user_playlists()
    exclude_list = set([x.split(':')[-1] for x in config.get('excluded_playlists', [])])
    playlists.extend([p for p in results['items'] if p['owner']['id'] == config['spotify']['username'] and not p['id'] in exclude_list])

    # get all the remaining playlists in parallel
    if results['next']:
        offsets = [ results['limit'] * n for n in range(1, math.ceil(results['total']/results['limit'])) ]
        extra_results = await atqdm.gather( *[asyncio.to_thread(spotify_session.current_user_playlists, offset=offset) for offset in offsets ] )
        for extra_result in extra_results:
            playlists.extend([p for p in extra_result['items'] if p['owner']['id'] == config['spotify']['username'] and not p['id'] in exclude_list])
    return playlists
```

**Comment by timrae** [comment]
Finally got to the bottom of this thanks to #80 . Should hopefully be fixed by the following, please let me know if that works:
https://github.com/spotify2tidal/spotify_to_tidal/commit/17d60c019d2991b5e66101fcd298001f8976c1f5

**Comment by Sildenafil99** [comment]
Sorry for the absence.
I updated to version 1.0 and made the changes to the file but it didn't solve my problem

PS C:\Temporary\spotify_to_tidal-1.0.0> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Loading playlists from Tidal user
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 7/7 [00:00<00:00, 22.20it/s]
Loading existing favorite tracks from Tidal
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.92it/s]
No new tracks to add to Tidal favorites

**Comment by Sildenafil99** [comment]
This is my sync.py

https://pastebin.com/waQ1sry9

**Comment by timrae** [comment]
What if you change the [following line](https://github.com/spotify2tidal/spotify_to_tidal/blob/main/src/spotify_to_tidal/sync.py#L386) to this?

```python
print( spotify_session.current_user() )
print( [ p['owner'] for p in playlists ] )
return playlists
```

A) Does it work?
B) Either way, can you share the output? or you can send privately to my gmail if you prefer, `perceptualchaos2`

**Comment by Sildenafil99** [comment]
PS C:\Temporary\spotify_to_tidal-1.0.0> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Loading playlists from Tidal user
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 7/7 [00:00<00:00, 20.36it/s]
Loading existing favorite tracks from Tidal
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.27it/s]
No new tracks to add to Tidal favorites
PS C:\Temporary\spotify_to_tidal-1.0.0>

Same result. Where I can find the output? This is the result

**Comment by timrae** [comment]
It would print to the terminal if you've modified the correct file. Most likely you have a previous installation which is running when you call `spotify_to_tidal` instead of the one you've modified.

**Comment by Sildenafil99** [comment]
I deleted the old installation and made a new one, same config file and copied the sync file, but now it doesn't start.
PS C:\Temporary\spotify_to_tidal-1.0.0> spotify_to_tidal
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Scripts\spotify_to_tidal.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'spotify_to_tidal'

**Comment by timrae** [comment]
Hi you'd need to run the following command, as written in the installation section of the readme:

```
python3 -m pip install -e .
```

**Comment by Sildenafil99** [comment]
Sorry I forgot to reinstall the new version

PS C:\Temporary\spotify_to_tidal-1.0.0> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Scripts\spotify_to_tidal.exe\__main__.py", line 7, in <module>
  File "C:\Temporary\spotify_to_tidal-1.0.0\src\spotify_to_tidal\__main__.py", line 38, in main
    _sync.sync_playlists_wrapper(spotify_session, tidal_session, _sync.get_user_playlist_mappings(spotify_session, tidal_session, config), config)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temporary\spotify_to_tidal-1.0.0\src\spotify_to_tidal\sync.py", line 361, in get_user_playlist_mappings
    spotify_playlists = asyncio.run(get_playlists_from_spotify(spotify_session, config))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Temporary\spotify_to_tidal-1.0.0\src\spotify_to_tidal\sync.py", line 372, in get_playlists_from_spotify
    print(results)
          ^^^^^^^
NameError: name 'results' is not defined. Did you mean: 'requests'?

**Comment by timrae** [comment]
You should wipe what you have and install fresh from the latest commit on `main` again, since it seems you didn't do that properly last time. If that doesn't work then I would go back to my [previous question](https://github.com/spotify2tidal/spotify_to_tidal/issues/73#issuecomment-2344722340).

**Comment by Sildenafil99** [comment]
output from new install:

PS C:\Temporary\spotify_to_tidal-1.0.0> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Loading playlists from Tidal user
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 7/7 [00:00<00:00, 21.26it/s]
Loading existing favorite tracks from Tidal
Fetching additional data chunks: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.56it/s]
Searching Tidal for 5/144 tracks in Spotify playlist 'Favorites': 100%|██████████████████| 5/5 [00:01<00:00,  3.29it/s]
Could not find the track 7g8pKtAeH3sKk75aKrIpDN: DJ Phellix,Johny Luv - Gentle Night
Could not find the track 08FUzof6NqG8kQEsNmkWDh: Bronski Beat,Bourlingueurs - Smalltown Boy (Remix)
Could not find the track 0bFaLfdRlQdgkg9MT7L8CQ: Edward Botero - No Man No Cry
Could not find the track 6Pq83UXbx8k2FXOS5BqXhi: Rivo,Armin van Buuren,Sharon Den Adel - In And Out Of Love
Adding new tracks to Tidal favorites: 100%|██████████████████████████████████████████████| 1/1 [00:00<00:00,  7.09it/s]

output with all mod:

PS C:\Temporary\spotify_to_tidal-1.0.0> spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Scripts\spotify_to_tidal.exe\__main__.py", line 7, in <module>
  File "C:\Temporary\spotify_to_tidal-1.0.0\src\spotify_to_tidal\__main__.py", line 38, in main
    _sync.sync_playlists_wrapper(spotify_session, tidal_session, _sync.get_user_playlist_mappings(spotify_session, tidal_session, config), config)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temporary\spotify_to_tidal-1.0.0\src\spotify_to_tidal\sync.py", line 361, in get_user_playlist_mappings
    spotify_playlists = asyncio.run(get_playlists_from_spotify(spotify_session, config))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smoke\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Temporary\spotify_to_tidal-1.0.0\src\spotify_to_tidal\sync.py", line 372, in get_playlists_from_spotify
    print(results)
          ^^^^^^^
NameError: name 'results' is not defined. Did you mean: 'requests'?

**Comment by timrae** [comment]
[Line 372](https://github.com/spotify2tidal/spotify_to_tidal/blob/main/src/spotify_to_tidal/sync.py#L372) does not look like `print(results)`, so I can clearly say that you have not done a fresh install

**Comment by Sildenafil99** [comment]
Sorry maybe I can't understand, do you want a new installation with the sync file modified with [this](https://github.com/spotify2tidal/spotify_to_tidal/issues/73#issuecomment-2344722340)?

**Comment by timrae** [comment]
First do a totally new installation using the latest commit on `main` (not v1.0.0) and check if it works

**Comment by timrae** [comment]
Second, only if it doesn't work, you can add the code in the comment you linked, and paste the result here

**Comment by Sildenafil99** [comment]
Ok, now it worked but I had to manually copy and paste the contents of the sync file from github to my file, this means that I did something wrong in the uninstallation and new installation.
These were my steps (on windows)
- I deleted the old folder
- I unpacked the spotify_to_tidal-1.0.0.zip file
- I opened a poweshell from the unpacked folder and then gave the commands:
py -m pip install -e .
spotify_to_tidal
and logged in to tidal.
What did I do wrong?
Thanks for your help

**Comment by timrae** [comment]
> Ok, now it worked
Great news!

> I had to manually copy and paste the contents of the sync file from github to my file

Yeah you'd need to do that to get the latest commit, otherwise according to your steps you'd still be on version 1.0.0, which doesn't have the latest commit

> What did I do wrong?

The expected and most easy installation method (in terms of updating the code) is to use git. 

```bash
git clone https://github.com/spotify2tidal/spotify_to_tidal.git
cd spotify_to_tidal
py -m pip install -e .
```

later when you want to update you should then just be able to do:

```bash
git pull
py -m pip install -e . # just to be safe, but only required if there are new files
```
